### ISSUE TITLE
Update time functions to use evm_setNextBlockTimestamp when using Hardhat Network

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-test-helpers#136]
Update time functions to use evm_setNextBlockTimestamp (Hardhat Network).
Currently uses `evm_increaseTime` (ganache-cli and Hardhat Network).

https://hardhat.org/hardhat-network/#special-testing-debugging-methods

Raised by Anatol: https://t.me/BuidlerSupport/10248

**Comment by frangio** [comment]
Took a better look at this and this is not too different from our current implementation. `setNextBlockTimestamp` is exactly like `increaseTime` except it takes an absolute timestamp to jump to, instead of a time duration to advance.

Anatol's comment in the Telegram group was based on the wrong assumption that we advance blocks in order to increase time, but they were looking at the code for `time.advanceBlockTo`, whose purpose _is_ advancing blocks, so there is nothing we can change about it at the moment.
