### ISSUE TITLE
expectEvent not working well with ethers/hardhat

### ISSUE THREAD

**Issue by mathijs81** [OpenZeppelin/openzeppelin-test-helpers#155]
I'm using hardhat to test a contract, but the expectEvent method is not working well with that.

When I do something like 
```
const { expect } = require("chai");
const { ethers } = require("hardhat");
const { expectEvent } = require('@openzeppelin/test-helpers');

[... setup contract etc. ...]

const transaction = await expect(MyContract.testMethod()).to.not.be.reverted
const receipt = await transaction.wait();
```
then the receipt has an `events` field that I can use properly with `expectEvent.inLogs(receipt.events, 'TestEvent')`, but this throws a deprecation warning "DeprecationWarning: expectEvent.inLogs() is deprecated. Use expectEvent() instead."

However, calling `expectEvent(receipt, 'TestEvent')` doesn't worked. I tested the existing code a bit, and noticed that `isWeb3Receipt(receipt)` is true, but the flatten code starting at `expectEvent.js:18` doesn't work well with this object because receipt.events is an array and not an object with named keys.

So can either `inLogs` not be deprecated or the expectEvent() code be changed so it handles this object better?

**Comment by abcoathup** [comment]
Hi @mathijs81!  I’m sorry that you had this issue.  We would need more information so that we can reproduce it.

Please note:
>OpenZeppelin Test Helpers is web3.js based, thus Hardhat users should use the Truffle plugin for compatibility, or use Waffle with ethers.js, which offers similar functionality.

_From: https://docs.openzeppelin.com/learn/writing-automated-tests#performing-complex-assertions_


Can you provide the version of the Test Helpers, web3, Truffle Plugin and hardhat you are using to run your tests? Any other details that might help us reproduce it would be appreciated!

**Comment by mathijs81** [comment]
Hi @abcoathup, thanks for the pointer, I didn't know it would be better to use waffle, I'll look into that!

**Comment by frangio** [comment]
To clarify, it's fine to use OpenZeppelin Test Helpers with Hardhat, it's just necessary to install the `hardhat-truffle5` plugin.

**Comment by psykeeper** [comment]
I was having a similar issue but was able to get it to work by:

1. Removing `chai-as-promised`
2. Installing `ethereum-waffle` 
3. Setting up `chai` with the following initialization code:

```javascript
const hre = require("hardhat");
const chai = require("chai");
const { solidity } = require("ethereum-waffle");
chai.use(solidity);
const { expect } = chai;
```

The issue I ran into was the `expect` object not having waffle's matchers. Specifically, `expect` didn't know about `reverted` without having `ethereum-waffle` installed and `chai` initialized with `solidity` from `ethereum-waffle`.

**Comment by advra** [comment]
@psykeeper I typically use Web3 and hardhat. This discussion is a bit old now so Id like to check if the method you mention is still okay to use? Or should I use hardhat only with web3 now?

**Comment by makinghappen** [comment]
@abcoathup When using openzeppelin-test-helpers with hardhat:
```
await expectEvent(createAuditorNFTReceipt, 'URI', {
      value: this.value,
    });
```
the Event object coming to the inLogs function in ExpectEvent.js has event ids as event names instead of actual event names, what causes this issue.

![image](https://user-images.githubusercontent.com/100151762/211870991-47039fbc-6515-49cd-b5b8-a2793b6bec2a.png)
![image](https://user-images.githubusercontent.com/100151762/211871080-9d2baf67-4e7f-4ed1-914f-f73b9eda5c10.png)
