### ISSUE TITLE
expectEvent doesn't check events emitted by nested contract calls

### ISSUE THREAD

**Issue by sibarum** [OpenZeppelin/openzeppelin-test-helpers#175]
Given I have contracts A and B, where A calls some method on B, and the method on B emits an event, I would expect the expectEvent method to find this event.

The expectEvent method iterates the events from receipt.events and receipt.logs, however the nested events only appear in receipt.rawLogs for some reason. I think if the code was changed to check rawLogs only, it would cover all scenarios.

**Comment by nventuro** [comment]
If I recall correctly, that is because logs are only decoded using the ABI of the original recipient of the transaction. You can use [`expectEvent.inTransaction`](https://docs.openzeppelin.com/test-helpers/0.5/api#intransaction), which accepts an extra `emitter` argument, to achieve what you're trying to do.

Note that unlike `expectEvent`, `inTransaction` is `async`, so you'll need to `await` the call.

**Comment by frangio** [comment]
> I think if the code was changed to check rawLogs only, it would cover all scenarios.

The issue with this is that we wouldn't know what ABI to use to decode the logs. This is why `expectEvent.inTransaction` receives an `emitter` argument that it can use to extract the ABI.
