### ISSUE TITLE
expectRevert unexpected behavior because of indexOf instead of ==

### ISSUE THREAD

**Issue by guylando** [OpenZeppelin/openzeppelin-test-helpers#44]
`await shouldFail.reverting.withMessage(this.safeMath.mul(a, b), 'SignedSafeMath: multiplication overflow');`
returned success even when contract had two requires one with `SignedSafeMath: multiplication overflow 1` and another with `SignedSafeMath: multiplication overflow 2`.
From looking at the code it seems it happens because of the use of "indexOf".
This seems like an unexpected behavior.

**Comment by nventuro** [comment]
Hello @guylando, thank you for noticing this!

Indeed, in order to only accept an exact match we'd have to do some parsing over the error string, and extract the revert reason from it (after testing behaviour on multiple nodes, AFAIK there's no standard error message format).

This is related to #33.

**Comment by nventuro** [comment]
Closed via https://github.com/OpenZeppelin/openzeppelin-test-helpers/pull/67
